export const GENERATE_NAME = 'GENERATE_NAME';

export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAIL = 'CREATE_PLAYER_FAIL';

export const POLL_LOBBY_SUCCESS = 'POLL_LOBBY_SUCCESS';
export const POLL_LOBBY_FAIL = 'POLL_LOBBY_FAIL';

export const SET_COUNTDOWN = 'SET_COUNTDOWN';

export const SET_CHOICE = 'SET_CHOICE';

export const PICK_CHOICE_SUCCESS = 'PICK_CHOICE_SUCCESS';
export const PICK_CHOICE_FAIL = 'PICK_CHOICE_FAIL';
